// product action types
export const FETCH_PRODUCT_REQUEST = 'FETCH_PRODUCT_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR =  'FETCH_PRODUCT_ERROR';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
export const EMPTY_CART =  'EMPTY_CART';
export const UPDATE_QTY =  'UPDATE_QTY';